services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - modelo1
      - modelo2

  modelo1:
    build: ./backend/models/modelo1
    container_name: modelo1
    expose:
      - "5001"

  modelo2:
    build: ./backend/models/modelo2
    container_name: modelo2
    expose:
      - "5002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 3s
      retries: 30

  modelo3:
    build: ./backend/models/modelo3
    container_name: modelo3
    expose:
      - "5003"

  modelo4:
    build: ./backend/models/modelo4
    container_name: modelo4
    expose:
      - "5004"
      
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
